services:
  nsfw-nats:
    container_name: nsfw-nats
    image: nsfw-nats:latest
    build:
      context: .
      args:
        API_VERSION: 11111
    environment:
      - NAT_URL=nats://nats_server:4222
      - NATS_ENDPOINT=nats://nats_server:4222
      - LOCAL_ENV=1
      - IMAGES_PATH=/app/images
      - IS_DOCKER=1
    volumes:
      - /mnt/d/repos2/pii-nats/nsfw/images:/app/images
    restart: always
    networks:
      - app-network
  
  
  nats_server:
    container_name: nats_server
    image: nats:latest
    environment:
      - USE_ONNX=YES
    command: -js
    ports:
      - 4222:4222
    restart: always
    networks:
      - app-network

# Define networks at the same level as services (not nested inside services)
networks:
  app-network:
    driver: bridge