version: "3.9"

services:


  mcpserver3:
    build: ./servers/server3
    container_name: mcpserver_3
    restart: always
    volumes:
      - ./servers/server3:/app
    ports:
      - "8002:8002"
      
  hostclient:
    build: ./client
    container_name: hostclient
    restart: always
    volumes:
      - ./client/:/app
    ports:
      - "8501:8501"
    command: >
      streamlit run app.py
    depends_on:
      - mcpserver3

