version: "3.9"

services:
  mcpserver3:
    build: ./servers/server3
    container_name: mcpserver_3
    restart: always
    volumes:
      - ./servers/server3:/app
    ports:
      - "8002:8002"

  mcpserver4:
    build: ./servers/server4
    container_name: mcpserver_4
    restart: always
    volumes:
      - ./servers/server4:/app
    ports:
      - "8003:8003"
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}
    env_file:
      - .env

  mcpserver5:
    build: ./servers/server5
    container_name: mcpserver_5
    restart: always
    volumes:
      - ./servers/server5:/app
    ports:
      - "8004:8004"
    environment:
      - PRIVATE_APP_ACCESS_TOKEN=${PRIVATE_APP_ACCESS_TOKEN}
      - HOST=0.0.0.0
      - PORT=8004
    env_file:
      - .env
      
  hostclient:
    build: ./client
    container_name: hostclient
    restart: always
    volumes:
      - ./client/:/app
    ports:
      - "8501:8501"
    command: >
      streamlit run app.py
    depends_on:
      - mcpserver3
      - mcpserver4
      - mcpserver5
    env_file:
      - .env