services:
  hostclient:
    build: ./client
    ports:
      - "8501:8501"
      - "8503:8503"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - PERPLEXITY_MODEL=${PERPLEXITY_MODEL}
      - SSL_ENABLED=${SSL_ENABLED}
    depends_on:
      - mcpserver1
      - mcpserver2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8503/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mcpserver1:
    build: ./servers/server1
    ports:
      - "8001:8001"
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - PERPLEXITY_MODEL=${PERPLEXITY_MODEL}
      - CACHE_TTL_SECONDS=1800
      - HEALTH_CHECK_TTL_SECONDS=300
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcpserver2:
    build: ./servers/server2
    ports:
      - "8002:8002"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
      - PORT=8002
      - HOST=0.0.0.0
      # REDUCED CACHE SETTINGS FOR LARGE DATASETS
      - SEARCH_CACHE_TTL_MINUTES=15
      - WEBPAGE_CACHE_TTL_HOURS=1
      - WEBPAGE_CACHE_MAX_SIZE=500
      - HEALTH_CHECK_TTL_MINUTES=5
      # MEMORY MANAGEMENT
      - NODE_OPTIONS=--max-old-space-size=6144
      - FORCE_GC_INTERVAL=300000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
        reservations:
          memory: 4G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Custom network for better container communication
networks:
  default:
    name: mcp_network
    driver: bridge