ES_TEST = {
    "collection_name": "PII Collection 1",
    "collection_type": "POPULATION",
    "analyses": [
        {
            "analysis": [
                {
                    "pii_type_detected": "TITLE",
                    "risk_level": 2,
                    "risk_level_definition": "Semi-Identifiable",
                    "cluster_membership_type": "Basic Demographics",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Not Mentioned",
                    "nist_category": "Linkable",
                    "entity_type": "TITLE",
                    "score": 1.0,
                    "start": 13,
                    "end": 18,
                },
                {
                    "pii_type_detected": "PHONE_NUMBER",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Contact Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Stand Alone PII",
                    "nist_category": "Directly PII",
                    "entity_type": "PHONE_NUMBER",
                    "score": 1.0,
                    "start": 86,
                    "end": 95,
                },
                {
                    "pii_type_detected": "ES_NIF",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Secure Identifiers",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Stand Alone PII",
                    "nist_category": "Directly PII",
                    "entity_type": "ES_NIF",
                    "score": 1.0,
                    "start": 108,
                    "end": 117,
                },
                {
                    "pii_type_detected": "PERSON",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Financial Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Linkable",
                    "nist_category": "Directly PII",
                    "entity_type": "PERSON",
                    "score": 0.85,
                    "start": 19,
                    "end": 47,
                },
                {
                    "pii_type_detected": "PHONE_NUMBER",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Contact Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Stand Alone PII",
                    "nist_category": "Directly PII",
                    "entity_type": "PHONE_NUMBER",
                    "score": 0.4,
                    "start": 66,
                    "end": 78,
                },
            ],
            "index": 0,
            "risk_score_mean": 2.8,
            "sanitized_text": "mi nombre es  <REDACTED>, y mi telefono es <REDACTED>, mobil <REDACTED> y mi nif es <REDACTED>",
        }
    ],
    "detection_count": 5,
    "risk_scores": [2.8],
    "risk_score_mean": 2.8,
    "risk_score_mode": 2.8,
    "risk_score_median": 2.8,
    "risk_score_standard_deviation": 0.0,
    "risk_score_variance": 0.0,
    "detected_pii_types": {"ES_NIF", "PERSON", "PHONE_NUMBER", "TITLE"},
    "detected_pii_type_frequencies": {
        "TITLE": 1,
        "PHONE_NUMBER": 2,
        "ES_NIF": 1,
        "PERSON": 1,
    },
}

ES_KEYS = {
    "analyses",
    "collection_name",
    "collection_type",
    "detected_pii_type_frequencies",
    "detected_pii_types",
    "detection_count",
    "risk_score_mean",
    "risk_score_median",
    "risk_score_mode",
    "risk_score_standard_deviation",
    "risk_score_variance",
    "risk_scores",
}

text_to_analyse = "mi nombre es señor Juan Salvador Huertas Romero, y mi telefono es +34976490844, mobil 665819952 y mi nif es 25152897M"
text_to_analyse_de = """Seit Aiwangers Bruder gesagt hat, dass er der Verfasser des Auschwitz-Pamphlets gewesen sei, stellen sich noch mehr Fragen. 
Sollte es so sein: Warum hatte Hubert Aiwanger es dann in der Tasche, warum ließ er sich dafür bestrafen? Sicher ist: In Bayern gerät dadurch jetzt vieles ins Wanken.
 Personalausweis 1220001297D Herr Huertas"""
DE_TEST = {
    "collection_name": "PII Collection 1",
    "collection_type": "POPULATION",
    "analyses": [
        {
            "analysis": [
                {
                    "pii_type_detected": "DE_ID_NUMBER",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Secure Identifiers",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Stand Alone PII",
                    "nist_category": "Directly PII",
                    "entity_type": "DE_ID_NUMBER",
                    "score": 1.0,
                    "start": 307,
                    "end": 318,
                },
                {
                    "pii_type_detected": "TITLE",
                    "risk_level": 2,
                    "risk_level_definition": "Semi-Identifiable",
                    "cluster_membership_type": "Basic Demographics",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Not Mentioned",
                    "nist_category": "Linkable",
                    "entity_type": "TITLE",
                    "score": 1.0,
                    "start": 319,
                    "end": 323,
                },
                {
                    "pii_type_detected": "PERSON",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Financial Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Linkable",
                    "nist_category": "Directly PII",
                    "entity_type": "PERSON",
                    "score": 0.85,
                    "start": 5,
                    "end": 21,
                },
                {
                    "pii_type_detected": "PERSON",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Financial Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Linkable",
                    "nist_category": "Directly PII",
                    "entity_type": "PERSON",
                    "score": 0.85,
                    "start": 155,
                    "end": 170,
                },
                {
                    "pii_type_detected": "LOCATION",
                    "risk_level": 2,
                    "risk_level_definition": "Semi-Identifiable",
                    "cluster_membership_type": "Secure Identifiers",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Not Mentioned",
                    "nist_category": "Linkable",
                    "entity_type": "LOCATION",
                    "score": 0.85,
                    "start": 245,
                    "end": 251,
                },
                {
                    "pii_type_detected": "PERSON",
                    "risk_level": 3,
                    "risk_level_definition": "Identifiable",
                    "cluster_membership_type": "Financial Information",
                    "hipaa_category": "Protected Health Information",
                    "dhs_category": "Linkable",
                    "nist_category": "Directly PII",
                    "entity_type": "PERSON",
                    "score": 0.85,
                    "start": 324,
                    "end": 331,
                },
            ],
            "index": 0,
            "risk_score_mean": 2.6666666666666665,
            "sanitized_text": "Seit <REDACTED> gesagt hat, dass er der Verfasser des Auschwitz-Pamphlets gewesen sei, stellen sich noch mehr Fragen. Sollte es so sein: Warum hatte <REDACTED> es dann in der Tasche, warum ließ er sich dafür bestrafen? Sicher ist: In <REDACTED> gerät dadurch jetzt vieles ins Wanken. Personalausweis <REDACTED>  <REDACTED>",
        }
    ],
    "detection_count": 6,
    "risk_scores": [2.6666666666666665],
    "risk_score_mean": 2.6666666666666665,
    "risk_score_mode": 2.6666666666666665,
    "risk_score_median": 2.6666666666666665,
    "risk_score_standard_deviation": 0.0,
    "risk_score_variance": 0.0,
    "detected_pii_types": {"DE_ID_NUMBER", "LOCATION", "PERSON", "TITLE"},
    "detected_pii_type_frequencies": {
        "DE_ID_NUMBER": 1,
        "TITLE": 1,
        "PERSON": 3,
        "LOCATION": 1,
    },
}

v2_columns = {
    "Cluster_Membership_Type",
    "Country",
    "DHS_Category",
    "GDPR Reference",
    "GDPR Reference URL",
    "GDPR_Category",
    "GDPR_Impact",
    "GDPR_Importance_Weighting",
    "GDPR_Risk_Score",
    "GDPR_Sensitivity",
    "GRPR_Likelihood",
    "HIPAA_Protected_Health_Information_Category",
    "Information Type Description ",
    "Information_Type",
    "NIST_Category",
    "PII_Category",
    "PII_Impact_Score",
    "PII_Importance_Weighting",
    "PII_Likelihood_Score",
    "PII_Risk_Score",
    "PII_Sensitivity_Score",
    "PII_Type",
    "Risk_Level",
    "Risk_Level_GDPR",
    "Risk_Level_PII",
}

v1_columns = {
    "Cluster_Membership_Type",
    "DHS_Category",
    "HIPAA_Protected_Health_Information_Category",
    "Information_Type",
    "NIST_Category",
    "PII_Type",
    "Risk_Level",
}


new_weigths = [
    {
        "PII_Type": "AGE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "ABA_ROUTING_NUMBER",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "United States",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "AU_ABN",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.69,
        "Risk_Level_GDPR": "High",
        "Country": "Australia",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "AU_ACN",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.69,
        "Risk_Level_GDPR": "High",
        "Country": "Australia",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "AU_MEDICARE",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Australia",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "DATE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "CREDIT_CARD",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "CRYPTO",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "DATE_TIME",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Basic Identifier",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "US_DRIVER_LICENSE",
        "GDPR_Category": "Pseudonymous Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Basic Identifier",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "EMAIL_ADDRESS",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Online Identifier",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "GENDER",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "DE_ID_NUMBER",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Germany",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "LOCATION",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 3,
        "GRPR_Likelihood": 3,
        "GDPR_Impact": 3,
        "GDPR_Importance_Weighting": 3,
        "GDPR_Risk_Score": 0.36,
        "Risk_Level_GDPR": "Low",
        "Country": "Universal",
        "PII_Category": "Geolocation Data",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "HEALTH_INSURANCE_ID",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Healthcare Information",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "HEIGHT",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "PHONE_NUMBER",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Contact Information",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IBAN_CODE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IP_ADDRESS",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Geolocation Data",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "JOB_TITLE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 3,
        "GRPR_Likelihood": 3,
        "GDPR_Impact": 3,
        "GDPR_Importance_Weighting": 3,
        "GDPR_Risk_Score": 0.36,
        "Risk_Level_GDPR": "Low",
        "Country": "Universal",
        "PII_Category": "Employment Information",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "MARITAL_STATUS",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 3,
        "GRPR_Likelihood": 3,
        "GDPR_Impact": 3,
        "GDPR_Importance_Weighting": 3,
        "GDPR_Risk_Score": 0.36,
        "Risk_Level_GDPR": "Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "MEDICAL_LICENSE",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Professional Licenses",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "NRP",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "OCCUPATION",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 3,
        "GRPR_Likelihood": 3,
        "GDPR_Impact": 3,
        "GDPR_Importance_Weighting": 3,
        "GDPR_Risk_Score": 0.36,
        "Risk_Level_GDPR": "Low",
        "Country": "Universal",
        "PII_Category": "Employment Information",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "US_PASSPORT",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "PERSON",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Basic Identifier",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "RACE",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "SEXUAL_PREFERENCE",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 3,
        "GDPR_Importance_Weighting": 3,
        "GDPR_Risk_Score": 0.44,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 4,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "SOCIAL_NETWORK_PROFILE",
        "GDPR_Category": "Pseudonymous Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Online Identifier",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "ES_NIF",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Spain",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "SWIFT_CODE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Universal",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "AU_TFN",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 0.93,
        "Risk_Level_GDPR": "Very High",
        "Country": "Australia",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "TITLE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.69,
        "Risk_Level_GDPR": "High",
        "Country": "Spain",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "UK_NHS",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "United Kingdom",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "US_BANK_NUMBER",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "United States",
        "PII_Category": "Financial Information",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "US_ITIN",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "United States",
        "PII_Category": "Online Identifier",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "URL",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 4,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.64,
        "Risk_Level_GDPR": "Medium",
        "Country": "Universal",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "US_SSN",
        "GDPR_Category": "Special Categories of Data (Sensitive Data)",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "United States",
        "PII_Category": "Vehicle Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "WEIGHT",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Contact Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "ZIPCODE",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 2,
        "GRPR_Likelihood": 2,
        "GDPR_Impact": 2,
        "GDPR_Importance_Weighting": 2,
        "GDPR_Risk_Score": 0.16,
        "Risk_Level_GDPR": "Very Low",
        "Country": "Universal",
        "PII_Category": "Demographic Information",
        "PII_Sensitivity_Score": 2,
        "PII_Likelihood_Score": 2,
        "PII_Impact_Score": 2,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "TITLE_EN",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 4,
        "GDPR_Impact": 4,
        "GDPR_Importance_Weighting": 4,
        "GDPR_Risk_Score": 0.69,
        "Risk_Level_GDPR": "High",
        "Country": "United States",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IT_FISCAL_CODE",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Italy",
        "PII_Category": "Online Identifier",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IT_DRIVER_LICENSE",
        "GDPR_Category": "Pseudonymous Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Italy",
        "PII_Category": "Basic Identifier",
        "PII_Sensitivity_Score": 3,
        "PII_Likelihood_Score": 3,
        "PII_Impact_Score": 3,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IT_VAT_CODE",
        "GDPR_Category": "Anonymous Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Italy",
        "PII_Category": "Online Identifier",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 4,
        "PII_Impact_Score": 4,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IT_PASSPORT",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Italy",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
    {
        "PII_Type": "IT_IDENTITY_CARD",
        "GDPR_Category": "Personal Data",
        "GDPR_Sensitivity": 5,
        "GRPR_Likelihood": 5,
        "GDPR_Impact": 5,
        "GDPR_Importance_Weighting": 5,
        "GDPR_Risk_Score": 1.0,
        "Risk_Level_GDPR": "Very High",
        "Country": "Italy",
        "PII_Category": "Security Identifiers",
        "PII_Sensitivity_Score": 5,
        "PII_Likelihood_Score": 5,
        "PII_Impact_Score": 5,
        "PII_Importance_Weighting": 5,
        "PII_Risk_Score": 0.5,
    },
]


PII_sample = """
Hello, my name is David Johnson and I live in Maine.
My credit card number is 4095-2609-9393-4932 and my crypto wallet id is 16Yeky6GMjeNkAiNcBY7ZhrLoMSgg1BoyZ.

On September 18 I visited microsoft.com and sent an email to olonok@presidio.com,  from the IP 192.168.0.1.

My passport: 191280342 and my phone number: (212) 555-1234.

This is a valid International Bank Account Number: IL150120690000003111111 . Can you please check the status on bank account 954567876544?

Kate's social security number is 078-05-1126.  Her driver license? it is 1234567A.

my bitcoin account is 3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5

The registration number of my company is ACN 004 085 616 and its url https://asic.gov.au/

My name is Doctor Asaf and my license number is BE1234563

take note of my email olonok@gmail.com

my coordenates are Account Number 36523492  IBAN GB12 TRWI 2314 7036 5234 92

My social security number is 856-45-6789
I live in London
check thse three numbers 33 051 775 556, 14 069 979 460 and 24 302 976 253 
you can check one of these three posibilities is in the US TAX form: 900700000 or 900 70 0000 or 900-70-0000
tell me if these are valid medicare number : 2123 45670 1 or 856 897 466

tell me what is this is a US Passport number 191280342

my Date of Birth is 14/04/1998

this is my security soccial number 717 653 4365

this is a correct tax number 123456782 ?

what is this? S9912345A

I am Republican , but I don't go regularly to thye church

it is S9912345A ,  a correct The National Registry Identification Number (NRIC) of Singapore? 
"""

PII_sample_extended = """A private burial ceremony took place in St Petersburg yesterday for the Wagner mercenary boss Yevgeny Prigozhin.

Most of the first group of people to visit the grave were members of the press, with only a handful of members of the public and people wearing Wagner insignia seen at the burial site, according to Reuters.

Secrecy surrounded arrangements for the closed funeral, meaning the event could not turn into a large-scale show of support for Prigozhin - whose massive mutiny in June amounted to the largest-ever threat to President Vladimir Putin's rule.

Putin did not attend yesterday's burial ceremony, according to the Kremlin.

Last week, Prigozhin was on a plane which crashed killing all ten people on board. Russian authorities have not said why the plane crashed, but the Kremlin has rejected speculation Putin ordered Prigozhin's death. 

Driving License Number 8013303159 Mr. Huertas.

She use to say that like to be recognized as transgender and gay. She has worked as doctor. she recognizes as being Lesbian, and he believes that he is straight. Their uncle recognizes as Asexual

He had a job as .net developer in PremCloud after he was separated from his wife

He is the only Aboriginal Australian I know, from all our work colleagues in Sidney office

My swift code is ABNABE2AIDJ and my routing number 325183233

my profile at crunchbase is http://crunchbase.com/organization/acme-corp and at github https://github.com/lorey/

my weight is 130.5 lb and my height is 1.85 meters. 

My syster is 30 years old
"""

PII_sample_it = """
Il codice fiscale del signore  Matteo Moretti è MRTMTT91D08F205J 
e il suo numero di patente do guida è RM7059065P
la sua partita iva italiana è 07643520567
Ongaro Edy, il suo numero di passaporto è AA1135734
La signora Anna Nowak ha una carta d'identità con il numero CA3081AA

Il mio codice swift è ABNABE2AIDJ

il mio profilo su crunchbase è http://crunchbase.com/organization/acme-corp e su github https://github.com/lorey/"""

PII_sample_es = """
Me llamo Juan i mi DNI es 25152897M, 
el nombre de mi banco es BANCO MEDIOLANUM
mi IBAN: ES43 01860079440507802411
el numero de BIC: BFIVESBB

y my perfil en crunchbase es http://crunchbase.com/organization/acme-corp, mi github es  https://github.com/lorey/
"""
PII_sample_de = """
Mein Name ist Juan, meine ID ist 25152897M und ich wohne in Zürich.
Der Name meiner Bank ist BANCO MEDIOLANUM
meine IBAN: ES43 01860079440507802411
BIC-Nummer: BFIVESBB

und mein Profil auf Crunchbase ist http://crunchbase.com/organization/acme-corp, mein Github ist https://github.com/lorey/
"""
dummy_set_analysis_results = {
    "analyses",
    "collection_name",
    "collection_type",
    "detected_pii_type_frequencies",
    "detected_pii_types",
    "detection_count",
    "risk_score_mean_gdpr",
    "risk_score_mean_pii",
    "risk_score_median_gdpr",
    "risk_score_median_pii",
    "risk_score_mode_gdpr",
    "risk_score_mode_pii",
    "risk_score_standard_deviation_gdpr",
    "risk_score_standard_deviation_pii",
    "risk_score_variance_gdpr",
    "risk_score_variance_pii",
    "risk_scores_gdpr",
    "risk_scores_pii",
}
dummy_set_analysis_results_v2 = set(
    {
        "detected_pii_type_frequencies",
        "detected_pii_types",
        "detection_count",
        "document_id",
        "entities",
        "file_name",
        "file_type",
        "file_uri",
        "language",
        "risk_score_mean_gdpr",
        "risk_score_mean_pii",
        "risk_score_median_gdpr",
        "risk_score_median_pii",
        "risk_score_mode_gdpr",
        "risk_score_mode_pii",
        "risk_score_standard_deviation_gdpr",
        "risk_score_standard_deviation_pii",
        "risk_score_variance_gdpr",
        "risk_score_variance_pii",
        "sanitized_text",
    }
)

dummy_entity_types = set(
    [
        "US_ITIN",
        "US_BANK_NUMBER",
        "IBAN_CODE",
        "AU_ABN",
        "EMAIL_ADDRESS",
        "CRYPTO",
        "SG_NRIC_FIN",
        "MEDICAL_LICENSE",
        "UK_NHS",
        "LOCATION",
        "US_PASSPORT",
        "DATE_TIME",
        "CREDIT_CARD",
        "URL",
        "NRP",
        "US_SSN",
        "PHONE_NUMBER",
        "AU_MEDICARE",
        "IP_ADDRESS",
        "US_DRIVER_LICENSE",
        "PERSON",
        "AU_ACN",
        "AU_TFN",
    ]
)
