# Registration Data Processing Configuration

# Pipeline step activation settings
pipeline_steps:
  # Data processing steps
  registration_processing: false
  scan_processing: false
  session_processing: false
  # Neo4j processing steps
  neo4j_visitor_processing: false
  neo4j_session_processing: false
  neo4j_job_stream_processing: false
  neo4j_specialization_stream_processing: false
  neo4j_visitor_relationship_processing: false
  session_embedding_processing: false
  session_recommendation_processing: true  # Enable session recommendation processing

# Input file paths
input_files:
  bva_registration: "data/bva/20250428_registration_BVA24_BVA25.json"
  lvs_registration: "data/bva/20250428_registration_LVS24.json"
  bva_demographic: "data/bva/20250428_demographics_BVA24_BVA25.json"
  lvs_demographic: "data/bva/20250428_demographics_LVS24.json"
  practices: "data/bva/practices_missing.csv"

# Scan data file paths
scan_files:
  session_this: "data/bva/BVA25_session_export.csv"
  session_past_bva: "data/bva/BVA24_session_export.csv"
  session_past_lva: "data/bva/LVA24_session_export.csv"
  seminars_scan_reference_past_bva: "data/bva/bva2024 seminar scans reference.csv"
  seminars_scans_past_bva: "data/bva/bva2024 seminar scans.csv"
  seminars_scan_reference_past_lva: "data/bva/lvs2024 seminar scans reference.csv"
  seminars_scans_past_lva: "data/bva/lvs2024 seminar scans.csv"

# Session data file paths
session_files:
  session_this: "data/bva/BVA25_session_export.csv"
  session_past_bva: "data/bva/BVA24_session_export.csv"
  session_past_lva: "data/bva/LVA24_session_export.csv"

# Stream processing configuration
stream_processing:
  use_cached_descriptions: true   # Set to true to use cached descriptions when available

# Embedding configuration
embeddings:
  model: "all-MiniLM-L6-v2"  # Model to use for generating session embeddings
  batch_size: 100            # Batch size for processing embeddings

# Session recommendation configuration
recommendation:
  min_similarity_score: 0.3   # Minimum similarity score (0.0-1.0) for recommendations
  max_recommendations: 10     # Maximum number of recommendations per visitor
  similar_visitors_count: 3   # Number of similar visitors to consider for new visitors
  use_langchain: true        # Whether to use LangChain for filtering (requires LangChain)
  rules_config:               # Rules configuration for filtering
    equine_mixed_exclusions: ["exotics", "feline", "exotic animal", "farm", "small animal"]
    small_animal_exclusions: ["equine", "farm animal", "farm", "large animal"]
    vet_exclusions: ["nursing"]
    nurse_streams: ["nursing", "wellbeing", "welfare"]
    rule_priority: ["practice_type", "role"]

# Neo4j configuration
neo4j:
  uri: "neo4j+s://c6cfaac8.databases.neo4j.io"
  username: "neo4j"
  password: ""  # Replace with actual password in production
  node_labels:
    visitor_this_year: "Visitor_this_year"
    visitor_last_year_bva: "Visitor_last_year_bva"
    visitor_last_year_lva: "Visitor_last_year_lva"
    session_this_year: "Sessions_this_year"
    session_past_year: "Sessions_past_year"
    stream: "Stream"
  unique_identifiers:
    visitor: "BadgeId"  # Field to use as unique identifier for visitor nodes
    session: "session_id"  # Field to use as unique identifier for session nodes
    stream: "stream"  # Field to use as unique identifier for stream nodes
  relationships:
    session_stream: "HAS_STREAM"  # Relationship between sessions and streams
    job_stream: "job_to_stream"  # Relationship between job roles and streams
    specialization_stream: "specialization_to_stream"  # Relationship between specializations and streams
    same_visitor: "Same_Visitor"  # Relationship between visitors this year and last year
    attended_session: "attended_session"  # Relationship between visitors and sessions they attended
  job_stream_mapping:
    file: "job_to_stream.csv"  # File containing job to stream mappings
  specialization_stream_mapping:
    file: "spezialization_to_stream.csv"  # File containing specialization to stream mappings
    specialization_map: {
      "Wildlife": "Other",
      "Small Animal": "Companion Animal",
      "Mixed": "Other", 
      "Dairy": "Farm",
      "Poultry": "Farm",
      "Cattle": "Farm",
      "Pigs": "Farm",
      "Sheep": "Farm"
    }
  visitor_relationship:
    same_visitor_properties:
      bva: { type: "bva" }  # Properties for BVA Same_Visitor relationships
      lva: { type: "lva" }  # Properties for LVA Same_Visitor relationships

# Default properties for visitor nodes
default_visitor_properties:
  Days_since_registration: "119"
  Country: "UK"
  Source: "BVA Key Stakeholders"
  Email_domain: "effem.com"
  assist_year_before: "1"
  job_role: "NA"
  what_type_does_your_practice_specialise_in: "NA"
  organisation_type: "NA"
  JobTitle: "NA"

# Environment file location
env_file: "keys/.env"

# Language model configuration
language_model:
  model: "gpt-4.1-mini"
  temperature: 0.5
  top_p: 0.9

# Output directory
output_dir: "data/bva/output"

# Event dates
event_date_this_year: "2025-06-12"
event_date_last_year: "2024-06-12"

# Valid badge types
valid_badge_types:
  - "Delegate"
  - "Delegate - Group"

# Shows for this year (for filtering)
shows_this_year:
  - "BVA2025"

# Questions to keep (for demographic analysis)
questions_to_keep:
  current:
    - "What type does your practice specialise in"
    - "Organisation Type"
    - "Job Role"
  past:
    - "What areas do you specialise in"
    - "Organisation Type"
    - "Job Role"

# Logging configuration
logging:
  level: "INFO"
  file: "data_processing.log"