name: pa-env
channels:
  - conda-forge
dependencies:
  - python=3.10.10
  - pip
  - scikit-learn
  - scipy
  - pandas
  - pip:  
    - azureml-mlflow
    - mlflow-skinny
    - azure-ai-ml
    - mltable
    - azure-identity
    - azure-keyvault-secrets
    - python-dotenv>=1.1.0
    - numpy<2
    - azureml-fsspec
    - neo4j
    - sentence-transformers
    - torch
    - transformers
    - fuzzywuzzy
    - orjson
    - openai
    - huggingface_hub[hf_xet]
    - PyYAML
    - langchain==0.3.23
    - langchain-community==0.3.21
    - langchain-core==0.3.51
    - langchain-openai==0.3.12
    - langchain-text-splitters==0.3.8
      
