FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    python3-dev \
    python3-setuptools \
    tesseract-ocr \
    libgl1 \
    make \
    gcc \
    libmagic1 \
    poppler-utils \
    unrtf \
    build-essential \
    libpoppler-cpp-dev \
    pkg-config \
    libreoffice \
    nano \
    net-tools \
    procps

RUN pip install --no-cache-dir --prefer-binary -r requirements.txt
ENV LOCAL_ENV="1"
ENV DOCS_PATH=/app/docs


COPY . .
EXPOSE 5003
CMD ["python", "endpoint_ocr_nats.py"]