version: "3.7"

services:

  ocr:
    container_name: ocr
    image: ocr:latest
    environment:
      - TESSDATA_PREFIX = /app/tessdata
    ports:
      - 5003:5003
    restart: always
    networks:
      - network
  nsfw:
    container_name: nsfw
    image: nsfw:latest
    environment:
      - USE_ONNX=YES
    ports:
      - 5009:5009
    restart: always
    networks:
      - network

  image_tagger:
    container_name: image_tagger
    image: image_tagger:latest
    environment:
      - USE_ONNX=YES
    ports:
      - 5011:5011
    restart: always
    networks:
      - network

  image_captioning:
    container_name: image_captioning
    image: image_captioning:latest
    environment:
      - USE_ONNX=YES
    ports:
      - 5010:5010
    restart: always
    networks:
      - network

  document_classification:
    container_name: document_classification
    image: document_classification:latest
    ports:
      - 5014:5014
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network

  document_summarization:
    container_name: document_summarization
    image: document_summarization:latest
    ports:
      - 5015:5015
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network
      
  admin_models:
    container_name: admin_models
    image: admin_models:latest
    ports:
      - 5016:5016
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../docker/configs/nginx/nginx-local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - ocr
      - nsfw
      - image_tagger
      - image_captioning
      - document_classification
      - document_summarization
      - admin_models
    networks:
      - network

networks:
  network:
