version: "3.7"

services:
  classification:
    container_name: classification
    image: acrdetectaideveastus.azurecr.io/detectai-classification:latest
    environment:
      - LOCAL_ENV = 0
    ports:
      - 5000:5000
    restart: always
    networks:
      - network

  rot:
    container_name: rot
    image: acrdetectaideveastus.azurecr.io/detectai-rot:latest
    ports:
      - 5007:5007
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/configs/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    depends_on:
      - classification
      - rot
    networks:
      - network

networks:
  network:
