# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Rev:r)-$(Build.BuildId) 

trigger:
  branches:
      include:
        - develop
  paths:
    include:
      - image/image_tagger-nats/*

pr:
  branches: 
    include:
      - develop 
  paths:
    include:
      - image/image_tagger-nats/*

resources:
  - repo: self

variables:
  # agents
  azure_build_Agent: "Azure Pipelines"
  hosted_build_Agent: "Default"
  Version: $(Build.BuildNumber)

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "b55a1ff0-774c-4842-8247-0fd90877ac37"
  imageRepository: "detectai"
  containerRegistry: "acrdetectaideveastus.azurecr.io"
  tag: "$(Build.BuildId)"

  # docker file paths
  dockerfilePath_image_tagger: "$(Build.SourcesDirectory)/image/image_tagger-nats/Dockerfile-tagger"
  dockerfilePath_image_captioning: "$(Build.SourcesDirectory)/image/image_tagger-nats/Dockerfile-captioner"

  # image Repositories
  imageRepository_image_tagger: "$(imageRepository)-image-tagger-nats"
  imageRepository_image_captioning: "$(imageRepository)-image-captioning-nats" 

  # Build Variables
  disable_tests: "false" # Set to 'true' to skip the unit tests
  use_no_cache: "false" # Set to 'true' to enable --no-cache which will build the docker images without cache

  # Sonar Cloud
  SonarCloud_Organization: "a5g3uqpot1ph"
  SonarCloud_ProjectName: "Detect-AI"
  SonarCloud_ProjectKey: "sceven_Detect-AI"

stages:
  - stage: Sonar_Analysis
    displayName: Sonar Analysis
    jobs:
      - job: Analyze
        displayName: Sonar Analysis
        pool: $(azure_build_Agent)
        steps:
          - checkout: self
            fetchDepth: 0

          - task: SonarCloudPrepare@3
            continueOnError: false
            inputs:
              SonarCloud: 'SonarCloud'
              organization: '$(SonarCloud_Organization)'
              scannerMode: 'CLI'
              configMode: 'file'
              extraProperties: |
                sonar.projectKey=$(SonarCloud_ProjectKey)
                sonar.organization=$(SonarCloud_Organization)

          - task: SonarCloudAnalyze@3
            continueOnError: false

          - task: SonarCloudPublish@3
            continueOnError: false
            inputs:
              pollingTimeoutSec: '300'

  - stage: Python_Integration_Tests
    displayName: Test Stage
    condition: eq(variables['disable_tests'], 'false')
    jobs:
      - job: RunUnitTests
        displayName: Run Tagger Python Unit Tests
        pool: $(azure_build_Agent)
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.10"
              addToPath: true

          # Add cache for pip with multiple requirements files
          - task: Cache@2
            inputs:
              key: 'pip | "$(Agent.OS)" | $(Build.SourcesDirectory)/tests/requirements.txt | $(Build.SourcesDirectory)/image/image_tagger-nats/requirements.txt | v1'
              restoreKeys: |
                pip | "$(Agent.OS)" | $(Build.SourcesDirectory)/tests/requirements.txt | $(Build.SourcesDirectory)/image/image_tagger-nats/requirements.txt
                pip | "$(Agent.OS)" | $(Build.SourcesDirectory)/tests/requirements.txt
                pip | "$(Agent.OS)"
              path: $(Pipeline.Workspace)/.pip          

          - script: |
              pip install --upgrade pip
              pip install --no-cache-dir -r $(Build.SourcesDirectory)/tests/requirements.txt --cache-dir $(Pipeline.Workspace)/.pip
              pip install --no-cache-dir -r $(Build.SourcesDirectory)/image/image_tagger-nats/requirements.txt --cache-dir $(Pipeline.Workspace)/.pip              
            displayName: Install Dependencies
            env:
              SPACY_DATA_PATH: $(Pipeline.Workspace)/.spacy

          - script: |
              python -m pytest tests -v -m "tagger"
            displayName: Run Tagger Unit Tests

          - script: |
              python -m pytest tests -v -m "captioner"
            displayName: Run Captioner Unit Tests

  - stage: Docker_Image_Tagger
    displayName: Docker Image Tagger
    jobs:
      - job: Docker_Image_Builds_Image_Tagger
        displayName: Build and Push Docker Image Tagger
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 
        pool: $(azure_build_Agent)
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: $(imageRepository_image_tagger)
              dockerfile: $(dockerfilePath_image_tagger)
              buildArguments: $[format('--no-cache={0}', variables['use_no_cache'])]
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
                $(Version)
              arguments: '--build-arg API_VERSION=$(Version)'
    dependsOn: Python_Integration_Tests

  - stage: Docker_Image_Captioning
    displayName: Docker Image Captioning
    jobs:
      - job: Docker_Image_Builds_Image_Captioning
        displayName: Build and Push Docker Image Captioning
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        pool: $(azure_build_Agent)
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: $(imageRepository_image_captioning)
              dockerfile: $(dockerfilePath_image_captioning)
              buildArguments: $[format('--no-cache={0}', variables['use_no_cache'])]
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
                $(Version)
              arguments: '--build-arg API_VERSION=$(Version)'
    dependsOn: Python_Integration_Tests