# Build Stage - used by devops pipeline
ARG API_VERSION

FROM python:3.11-slim

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt

RUN apt-get update && apt-get install python3-pip  ffmpeg libsm6 libxext6 git -y

RUN pip install --no-cache-dir --prefer-binary -r requirements.txt 
RUN pip install "openvino>=2024.3.0" "einops" "torch>2.1" "torchvision" "timm>=0.9.8" \
                "transformers>=4.41" "pillow" --extra-index-url https://download.pytorch.org/whl/cpu

# this variable tell the code which task to run, it can be either "tagger" or "caption"
ENV DOCKER_TASK=caption
ENV IS_DOCKER=1
ENV LOCAL_ENV="0"
ARG API_VERSION
ENV APPLICATIONVERSION=${API_VERSION}

# Echo the build version for verification
RUN echo "Build version: [v $API_VERSION ]"
RUN echo "Application version: [v $APPLICATIONVERSION ]"
RUN echo "Docker TASK version: [v $DOCKER_TASK ]"
RUN echo "Is Docker : [v $IS_DOCKER ]"

COPY . .

CMD ["python", "main.py"]