[server]
# Disable file watcher for better stability
fileWatcherType = "none"

# Optional: You can also use "poll" instead of "none" if you want file watching but more stable
# fileWatcherType = "poll"

[browser]
# Optionally disable auto-refresh on file changes
gatherUsageStats = false

[runner]
# Disable magic that can cause issues
magicEnabled = false

[client]
# Show errors in the browser
showErrorDetails = true