services:

  ollama1:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollamaa:/root/.ollama
    container_name: ollama1
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - ollama
      
  ollama2:
    image: ollama/ollama:latest
    ports:
      - 11435:11434
    volumes:
      - .:/code
      - ./ollama/ollamab:/root/.ollama
    container_name: ollama2
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - ollama

  elastic_llm:
    container_name: elastic_llm
    image: elastic-llm:latest

    ports:
      - 8133:8133
    restart: always
    networks:
      - ollama
      
  admin_models:
    container_name: admin_models
    image: admin_models:latest
    ports:
      - 5016:5016
    restart: always
    networks:
      - ollama
  pii_dicom:
    container_name: pii_dicom
    image: pii-dicom:latest
    ports:
      - 8155:8155
    volumes:
      - ../../../../data:/app/data    
    restart: always
    networks:
      - ollama

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../../../../docker/configs/nginx/nginx-elastic.conf:/etc/nginx/nginx.conf
      - ../../../../docker/configs/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    depends_on:
      - elastic_llm
    restart: always
    networks:
      - ollama
      
networks:
  ollama: