credentials:
  usernames:
    juan:
      email: olonok@gmail.com
      name: Juanito 
      password: $2b$12$ZxztXAbTDkS5tuNtQrHhUOhavCNGR65ajTcwkj.Z4J8ccqwlan22S # To be replaced with hashed password
    giovanni_romero:
      email: g.romero@closerstillmedia.com
      name: Giovanni Romero
      password: $2b$12$FFrlNwUaeFcsEhfVGhsjfO5eeTseV5QVZeOxL9TAir8VIaqiTeNS. # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: laPalma50 # Must be string
  name: thecokkei
preauthorized:
  emails:
  - olonok@gmail.com
  - g.romero@closerstillmedia.com