version: "3.7"

services:

  ocr:
    container_name: ocr
    image: acrdetectaideveastus.azurecr.io/detectai-ocr:${AI_BUILD_ID}
    volumes:
      - ../../models/image/ocr/tessdata:/app/tessdata
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - TESSDATA_PREFIX=${TESSDATA_PREFIX}
    ports:
      - 5003:5003
    restart: always
    networks:
      - network

  nsfw:
    container_name: nsfw
    image: acrdetectaideveastus.azurecr.io/detectai-nsfw:${AI_BUILD_ID}
    volumes:
      - ../../models/image/nsfw:/app/models
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - USE_ONNX=YES
    ports:
      - 5009:5009
    restart: always
    networks:
      - network

  image_tagger:
    container_name: image_tagger
    image: acrdetectaideveastus.azurecr.io/detectai-image_tagger:${AI_BUILD_ID}
    volumes:
      - ../../models/image/image_tagger:/image_tagger/models
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - USE_ONNX=YES
    ports:
      - 5011:5011
    restart: always
    networks:
      - network

  image_captioning:
    container_name: image_captioning
    image: acrdetectaideveastus.azurecr.io/detectai-image_captioning:${AI_BUILD_ID}
    volumes:
      - ../../models/image/image_captioning:/image_captioning/models
    environment:
      - LOCAL_ENV=${LOCAL_ENV}
      - USE_ONNX=YES
    ports:
      - 5010:5010
    restart: always
    networks:
      - network

  document_classification:
    container_name: document_classification
    image: acrdetectaideveastus.azurecr.io/detectai-document_classification:${AI_BUILD_ID}
    volumes:
      - ../../models/nlp/document_classification:/document_classification/models
    ports:
      - 5014:5014
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network

  document_summarization:
    container_name: document_summarization
    image: acrdetectaideveastus.azurecr.io/detectai-document_summarization:${AI_BUILD_ID}
    volumes:
      - ../../models/nlp/document_summarization:/document_summarization/models
    ports:
      - 5015:5015
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ../../ollama/code:/code
      - ../../ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    networks:
      - network

  admin_models:
    container_name: admin_models
    image: acrdetectaideveastus.azurecr.io/detectai-admin_models:${AI_BUILD_ID}
    ports:
      - 5016:5016
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../../docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../docker/configs/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    depends_on:
      - ocr
      - nsfw
      - image_tagger
      - image_captioning
      - document_classification
      - document_summarization
      - admin_models
    restart: always
    networks:
      - network

networks:
  network:
